name: Deploy to Server

on:
  push:
    branches:
      - tauri-memories-list  # Твоя ветка. Изменения в ней запустят процесс.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. Загружаем NVM в текущую сессию
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # 2. Переключаемся на 20-ю версию Node
            nvm use 20
            
            # 3. Теперь идем в проект
            cd /root/ListOfPreciousCharacters/pdcsw
            
            # 4. Чистим старые хвосты (иногда полезно при смене версий)
            rm -rf node_modules package-lock.json
            
            # 5. Установка и билд
            git pull origin tauri-memories-list
            npm install
            npm run build