name: Deploy to Server

on:
  push:
    branches:
      - tauri-memories-list  # Твоя ветка. Изменения в ней запустят процесс.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Принудительно загружаем NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # Активируем Node 20
            nvm use 20 || nvm install 20
            
            # Теперь идем в проект
            cd /root/ListOfPreciousCharacters/pdcsw
            
            # Исправляем права на ключ внутри скрипта на всякий случай
            chmod 600 /root/.ssh/id_ed25519
            
            # Обновляем код
            git pull origin tauri-memories-list
            
            # Очистка и установка (rm -rf гарантирует, что не будет конфликтов версий)
            rm -rf node_modules package-lock.json
            npm install
            
            # Билд
            npm run build