name: Deploy

on:
  push:
    branches:
      - tauri-memories-list  # Твоя ветка. Изменения в ней запустят процесс.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. Загружаем NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 20

            # Переходим в папку проекта
            cd /root/ListOfPreciousCharacters/pdcsw
            
            # Скачиваем обновления
            git pull origin tauri-memories-list
            
            # 2. КРИТИЧЕСКИЙ ШАГ: Удаляем старые модули и старый lock-файл
            # Это нужно сделать обязательно из-за смены версии Node
            rm -rf node_modules package-lock.json
            
            # 3. Чистим кэш npm на всякий случай
            npm cache clean --force

            # 4. Ставим всё заново (теперь под Node 20)
            npm install
            
            # Собираем проект
            npm run build
