name: Deploy

on:
  push:
    branches:
      - tauri-memories-list  # Твоя ветка. Изменения в ней запустят процесс.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. Загружаем NVM в текущую сессию (важно для non-interactive shell)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # 2. Переключаемся на 20-ю версию
            nvm use 20
            
            # Переходим в папку проекта
            cd /root/ListOfPreciousCharacters/pdcsw
            
            # Скачиваем обновления
            git pull origin tauri-memories-list
            
            # 3. Полная очистка перед установкой (нужно сделать один раз после смены версии Node)
            # Если билд все равно падает, раскомментируй строку ниже:
            # rm -rf node_modules package-lock.json
            
            # Устанавливаем зависимости
            npm install
            
            # Собираем проект
            npm run build
